### ISSUE TITLE
Missing dependencies for cpanm installed perl modules on debian stretch

### ISSUE THREAD

**Issue by laborg** [phoenixctms/install-debian#4]
Following dependencies are missing from `install.sh`:

`libtest-utf8-perl libmoose-perl libmoosex-hasdefaults-perl `

Without those the cpanm installation of

```
cpanm Dancer::Plugin::I18N
cpanm Spreadsheet::Reader::Format
cpanm Spreadsheet::Reader::ExcelXML
```
fails on a fresh debian stretch installation fails as of 04.04.2019.

**Comment by rkrenn** [comment]
- libtest-utf8-perl
- libmoosex-hasdefaults-perl

are added to make  

- cpanm Spreadsheet::Reader::Format
- cpanm Spreadsheet::Reader::ExcelXML

work again.
